imports:
  - { resource: tasks.phpcsfixer2.config.yml }

parameters:
  process_timeout: 3600
  ascii:
    failed: ~
    succeeded: ~

  # PHP Code Sniffer parameters.
  tasks.phpcs.ignore_patterns:
    - vendor/
    - node_modules/
    - tests/fixtures/
    - spec
  tasks.phpcs.triggered_by:
    - inc
    - install
    - module
    - php
    - profile
    - theme
  tasks.phpcs.whitelist_patterns: []
  tasks.phpcs.standard: ./vendor/drupal/coder/coder_sniffer/Drupal
  tasks.phpcs.show_warnings: true

  # Tasks.
  tasks:
    # PHP Lint
    phplint:
      triggered_by: ['php', 'module', 'install', 'profile', 'inc']
      metadata:
        priority: 5000

    # PHP CS Fixer
    phpcsfixer2:
      config: '%tasks.phpcsfixer2.config%'
      config_contains_finder: true
      verbose: true
      allow_risky: true
      using_cache: false
      metadata:
        priority: 4000

    # PHP Code Sniffer.
    phpcs:
      standard: '%tasks.phpcs.standard%'
      ignore_patterns: '%tasks.phpcs.ignore_patterns%'
      triggered_by: '%tasks.phpcs.triggered_by%'
      whitelist_patterns: '%tasks.phpcs.whitelist_patterns%'
      show_warnings: '%tasks.phpcs.show_warnings%'
      metadata:
        priority: 3000

    # YAML Lint
    yamllint:
      whitelist_patterns: []
      ignore_patterns: []
      object_support: true
      exception_on_invalid_type: true
      parse_constant: true
      parse_custom_tags: true
      metadata:
        priority: 2000

    # JSON Lint
    jsonlint:
      ignore_patterns: []
      detect_key_conflicts: true
      metadata:
        priority: 1000
